# -*- mode: python ; coding: utf-8 -*-
import sys
import os
from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_submodules


ROOT = Path(SPECPATH).resolve().parent
ENTRYPOINT = ROOT / "tools" / "clipflow_entry.py"
ICNS = ROOT / "build-helper" / "ClipFlow.icns"
ICO = ROOT / "build-helper" / "ClipFlow.ico"
WINSPARKLE_DLL = (
    ROOT
    / "build-helper"
    / "third_party"
    / "winsparkle"
    / "WinSparkle-0.9.3"
    / ("x64" if sys.maxsize > 2**32 else "x86")
    / "Release"
    / "WinSparkle.dll"
)
APP_VERSION = os.environ.get("CLIPFLOW_VERSION", "0.0.0")
APP_BUILD = os.environ.get("CLIPFLOW_BUILD_NUMBER", APP_VERSION)
CODESIGN_IDENTITY = os.environ.get("CLIPFLOW_CODESIGN_IDENTITY") or None
ENTITLEMENTS_FILE = os.environ.get("CLIPFLOW_ENTITLEMENTS_FILE") or None
BUILD_CONFIG_PATH = ROOT / "tools" / "clipflow_build_config.py"
WIN_FEED_URL = os.environ.get("CLIPFLOW_WINSPARKLE_FEED_URL") or os.environ.get("CLIPFLOW_SPARKLE_FEED_URL") or ""
WIN_PUBLIC_ED_KEY = os.environ.get("CLIPFLOW_SPARKLE_PUBLIC_ED_KEY") or ""
BUILD_CONFIG_PATH.write_text(
    "# Generated by ClipFlow.spec. Do not edit by hand.\n"
    f"VERSION = {APP_VERSION!r}\n"
    f"BUILD_NUMBER = {APP_BUILD!r}\n"
    f"FEED_URL = {WIN_FEED_URL!r}\n"
    f"PUBLIC_ED_KEY = {WIN_PUBLIC_ED_KEY!r}\n",
    encoding="utf-8",
)

# EXE icon must match the platform: .ico on Windows, .icns on macOS.
if sys.platform == "darwin":
    EXE_ICON = str(ICNS) if ICNS.exists() else None
elif sys.platform.startswith("win"):
    EXE_ICON = str(ICO) if ICO.exists() else None
else:
    EXE_ICON = None

datas = [
    (str(ROOT / "assets" / "icons" / "app_icon.png"), "assets/icons"),
    (str(ROOT / "assets" / "icons" / "lucide"), "assets/icons/lucide"),
]
binaries = []
hiddenimports = []
unused_large_modules = [
    "PIL",
    "Image",
    "ImageTk",
    "numpy",
    "numpy.libs",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtQml",
    "PySide6.QtQmlModels",
    "PySide6.QtQuick",
    "PySide6.QtQuickWidgets",
]
unused_qt_binaries = [
    "PySide6\\Qt6Pdf.dll",
    "PySide6\\Qt6Qml.dll",
    "PySide6\\Qt6QmlMeta.dll",
    "PySide6\\Qt6QmlModels.dll",
    "PySide6\\Qt6QmlWorkerScript.dll",
    "PySide6\\Qt6Quick.dll",
]


def without_unused_binaries(toc):
    filtered = []
    for item in toc:
        name = str(item[0]).replace("/", "\\").lower()
        if any(name.endswith(binary.lower()) for binary in unused_qt_binaries):
            continue
        filtered.append(item)
    return filtered


def mac_info_plist():
    info = {
        "CFBundleDisplayName": "ClipFlow",
        "CFBundleShortVersionString": APP_VERSION,
        "CFBundleVersion": APP_BUILD,
        "NSHighResolutionCapable": True,
    }
    sparkle_feed_url = os.environ.get("CLIPFLOW_SPARKLE_FEED_URL") or ""
    sparkle_public_key = os.environ.get("CLIPFLOW_SPARKLE_PUBLIC_ED_KEY") or ""
    if sparkle_feed_url or sparkle_public_key:
        if not sparkle_feed_url or not sparkle_public_key:
            raise ValueError("Set both CLIPFLOW_SPARKLE_FEED_URL and CLIPFLOW_SPARKLE_PUBLIC_ED_KEY for Sparkle builds.")
        info.update(
            {
                "SUFeedURL": sparkle_feed_url,
                "SUPublicEDKey": sparkle_public_key,
                "SUEnableAutomaticChecks": True,
                "SUAutomaticallyUpdate": True,
                "SUAllowsAutomaticUpdates": True,
            }
        )
    return info

hiddenimports += collect_submodules("yt_dlp")
hiddenimports += [
    "PySide6.QtSvg",
    "tools.clipflow_analysis_process",
    "tools.clipflow_build_config",
    "tools.clipflow_download_process",
    "tools.clipflow_qt",
]

for package in ("imageio_ffmpeg", "yt_dlp_ejs", "curl_cffi"):
    tmp_ret = collect_all(package)
    datas += tmp_ret[0]
    binaries += tmp_ret[1]
    hiddenimports += tmp_ret[2]

if sys.platform.startswith("win") and WINSPARKLE_DLL.exists():
    binaries.append((str(WINSPARKLE_DLL), "."))


a = Analysis(
    [str(ENTRYPOINT)],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["electron", *unused_large_modules],
    noarchive=False,
    optimize=0,
)
a.binaries = without_unused_binaries(a.binaries)
a.datas = without_unused_binaries(a.datas)
pyz = PYZ(a.pure)

if sys.platform == "darwin":
    # macOS: onedir (faster startup + recommended for .app bundles).
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="ClipFlow",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=CODESIGN_IDENTITY,
        entitlements_file=ENTITLEMENTS_FILE,
        icon=EXE_ICON,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name="ClipFlow",
    )
    app = BUNDLE(
        coll,
        name="ClipFlow.app",
        icon=str(ICNS) if ICNS.exists() else None,
        bundle_identifier="com.clipflow.app",
        info_plist=mac_info_plist(),
    )
else:
    # Windows/Linux: onefile (single distributable executable).
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name="ClipFlow",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=EXE_ICON,
    )
